In [3]:
import pandas as pd

In [13]:
data = {
    "temp":[30,32,34,36,38],
    "humid":[70,68,66,64,62]
}
df = pd.DataFrame(data)

In [14]:
df

temp  humid
0    30     70
1    32     68
2    34     66
3    36     64
4    38     62

In [15]:
df.cov()

temp  humid
temp   10.0  -10.0
humid -10.0   10.0

In [16]:
df.corr()

temp  humid
temp    1.0   -1.0
humid  -1.0    1.0

In [19]:
data = {
    "temp":[30,32,34,36,38],
    "humid":[70,68,72,60,62]
}
df = pd.DataFrame(data)

In [20]:
df

temp  humid
0    30     70
1    32     68
2    34     72
3    36     60
4    38     62

In [15]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import pandas as pd

In [14]:
import pandas as pd
s = pd.Series([1000,2000,3000,5000,9000])
s

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

# Normalization

In [5]:
s.min()

1000

In [6]:
s.max()

9000

In [7]:
s_norm = (s-s.min())/(s.max()-s.min())
print(s_norm)

0    0.000
1    0.125
2    0.250
3    0.500
4    1.000
dtype: float64


In [17]:
s_norm = MinMaxScaler().fit_transform(s.values.reshape(-1,1))
print(s_norm)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.5  ]
 [1.   ]]


In [19]:
df = pd.DataFrame({
    "temp":[20,25,30,35,40],
    "humid":[30,45,60,70,90]
})
df

temp  humid
0    20     30
1    25     45
2    30     60
3    35     70
4    40     90

In [22]:
norm_data = MinMaxScaler().fit_transform(df)
norm_data

array([[0.        , 0.        ],
       [0.25      , 0.25      ],
       [0.5       , 0.5       ],
       [0.75      , 0.66666667],
       [1.        , 1.        ]])

In [29]:
norm_df = pd.DataFrame(norm_data, columns=df.columns)
norm_data

array([[0.        , 0.        ],
       [0.25      , 0.25      ],
       [0.5       , 0.5       ],
       [0.75      , 0.66666667],
       [1.        , 1.        ]])

# Standardization

In [30]:
import pandas as pd
s = pd.Series([1000,2000,3000,5000,9000])
s

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

In [31]:
s.mean()

np.float64(4000.0)

In [32]:
s.std()

3162.2776601683795

In [36]:
z_Score = (s-s.mean())/s.std()
print(z_Score)

0   -0.948683
1   -0.632456
2   -0.316228
3    0.316228
4    1.581139
dtype: float64


In [37]:
z_Score = StandardScaler().fit_transform(s.values.reshape(-1,1))
print(z_Score)

[[-1.06066017]
 [-0.70710678]
 [-0.35355339]
 [ 0.35355339]
 [ 1.76776695]]


In [39]:
z_Score = (s-s.mean())/s.std(ddof=0)
print(z_Score)

0   -1.060660
1   -0.707107
2   -0.353553
3    0.353553
4    1.767767
dtype: float64


In [38]:
df = pd.DataFrame({
    "temp":[20,25,30,35,40],
    "humid":[30,45,60,70,90]
})
df

temp  humid
0    20     30
1    25     45
2    30     60
3    35     70
4    40     90